clc;
close all;
clear all;
AP=input('Enter passband gain = ');
AS=input('Enter stopband gain = ');
wp=input('Enter passband edge frequency = ');
ws=input('Enter stopband edge frequency = ');
alpha_p= -20*log10(AP); 
alpha_s= -20*log10(AS);
T=1;
WP=(2/T)*tan((wp)/2);
WS=(2/T)*tan((ws)/2);
[N,CF]=buttord(WP,WS,alpha_p,alpha_s,'s');
[B,A]=butter(N,CF, 'high','s');
disp('butterworth transfer function is');
HS=tf(B,A); printsys(B,A);
[num,den]=bilinear(B,A,1/T);
HZ=tf(num, den);
printsys(num, den, 'z');
w=0:0.01:pi;
h=freqz(num,den,w);
mag=abs(h);
plot(w/pi, mag);
title("Magnitude response of butterworth filter");
xlabel('Normalised frequency,\omega/\pi','fontweight', 'b');
ylabel('Magnitude', 'fontweight','b');