clc;
clear all;
close all;
t=(0:0.01:1);
f1=input('Enter first frequency = ');
f2=input('Enter second frequency = ');
y=6*sin(2*pi*f1*t)+3*cos(2*pi*f2*t);
figure(1);
subplot(3,1,1);
plot(t,y);
title('continous signal');
xlabel('t-->');
ylabel('x(t)-->');
f=max(f1,f2);
fs=2*f;
ts=1/fs;
to=0:ts:1;
ys=6*sin(2*pi*f1*to)+3*cos(2*pi*f2*to);
subplot(3,1,2);
stem(to,ys);
title('nyquist sampling');
xlabel('n-->');
ylabel('x(n)-->');
subplot(3,1,3);
plot(to,ys);
grid on;
xlabel('t-->');
ylabel('x(t)-->');
title('reconstuction');